project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Keao Hohtri's web"
  site-url: https://ucashjh.github.io
  favicon: images/Math&Gravity-logo.png
  repo-url: https://github.com/ucashjh/keao.github.io
  repo-actions: [edit, issue]
  
  page-footer:
    left: |
      Nothing in the left<br>
    right: |
      Nothing in the right<br>
    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications and Sources"
        href: publications.qmd
      - text: "Life"
        href: life.qmd
      - text: "Codes"
        href: codes.qmd
      - text: "中文(Chinese)"
        href: Chinese.qmd
      - text: "CV"
        href: CV.pdf

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细