---
title: "中文简历"
editor: 
  markdown: 
    wrap: 72
---

## 个人简介

何杰豪, 硕士生. 2022毕业于华南农业大学电子工程学院,或理学学士学位; 2023年就读于中国科学院大学杭州高等研究院,凝聚态物理专业.

- 邮箱：hejiehao23@mails.ucas.ac.cn
- Github: <https://github.com/ucashjh>
- 小红书：<https://www.xiaohongshu.com/user/profile/61a31e790000000010007c40>

## 教育和工作背景
- 2018.09-2022.06 华南农业大学 光电信息科学 本科
- 2022.06-2023.07 家教
- 2023.09-Present 中国科学院 凝聚态物理 硕士在读


## 学习课程
- 分析学: 数学分析, 实分析, 复分析, 泛函分析, 偏微分方程
- 代数学: 线性代数, 抽象代数, 代数拓扑, Lie代数
- 几何学: 点集拓扑, 微分流形, 黎曼几何, FInsler几何
- 物理学: 数学物理方法, 广义相对论, 现代宇宙学, 高等量子力学(没学明白)


## 研究兴趣

- 几何分析
- 数学物理(广义相对论与引力理论,应用偏微分方程)
- 偏微分方程


## 爱好

- 摄影
- 旅行
- 骑行





## 科研经历
1.2024年4月-2024年10月.跟随博后做第一性原理计算,主要是利用仿真软件搭建材料器件结构,探究材料特性,并设计合适的器件结构. 在研究中主要关注CrXY这类载流子迁移率高的材料(其中X为氧/硫,Y为卤族元素),该体系的最大特点是具有PGE效应,即非中心对称材料遇到光照时无需外置电场可产生光电流(光电效应).不仅如此,该材料还具备磁光效应和自旋极化效应,是非常有应用前景的.

2.2024年10-2025-4月.我参与Ai-agent项目,在项目初期我开始学Python和Pytorch,参与大语言模型的发展调研.在2025年初开始利用Coze平台搭建智能体协助课堂教学,我主要承担训练数据和资源收集(主要利用OCR把资源转化为markdown格式资源),Prompt工程优化,Workflow搭建.在完成了初步agent后,需要开发界面和配置后端,由于本人后续要追求学术因此只参与了部分界面的开发,后续工作交给了合作的同门完成.

3.2025年1月-2025年6月.我利用机器学习结合材料科学,进行钙钛矿太阳能电池的机器学习回归任务.为了实现机器学习与材料科学的结合,我需要进行数据收集与筛选、模型的训练和调参、模型的评估和可视化模型效果，最终利用1028个人工筛选的数据集并选择了6个传统的机器学习模型进行回归任务.本任务主要借助Sk-learn机器学习包进行并利用R语言完成数据可视化探索和分析.本人承担所有的研究工作,并用Latex完成了一篇个人论文,目前论文交给了博后修改,博后计划加入DFT计算补充说明并于2025年下半年完成论文发表.

4.2025年6月-现在.参加了厦门大学Finsler几何暑假学校和北京大学应用数学暑假学校,后续计划寻找数学科研工作,为后续读博增加研究经历和加强专业知识.